name: Run SSHX Command

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-sshx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run SSHX Command
        run: |
          curl -sSf https://sshx.io/get | sh -s run
